on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dagger/dagger-for-github@v8.2.0
        with:
          call: >-
            build-and-deploy
            --key env://DOTENV_PRIVATE_KEY_PREVIEW
            --env preview
        env:
          DOTENV_PRIVATE_KEY_PREVIEW: ${{ secrets.DOTENV_PRIVATE_KEY_PREVIEW }}
